#!/bin/sh

echo "Before:"
cat $FAI_ROOT/etc/apt/sources.list

sed -i \
    -e 's|repo.kali.org|kali.download|g' \
    -e 's|http://.*/kali |http://kali.download/kali |g' \
    -e 's/kali-last-snapshot/kali-rolling/g' \
    $FAI_ROOT/etc/apt/sources.list

echo "After:"
cat $FAI_ROOT/etc/apt/sources.list

chroot $FAI_ROOT apt-get update

# Enable ssh on boot, otherwise we're stuck
chroot $FAI_ROOT systemctl enable ssh
